export const dataDocumentoRecepcion = [
    {
        nro: 1,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 2,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 3,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 4,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 5,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 6,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 7,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 8,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 9,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 10,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 11,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 12,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 13,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
    {
        nro: 14,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },

    {
        nro: 15,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        fecha_entrega: '22/05/2022',
        referencia:'71237331',
        cotizacion: 90,
        anticipo: 20,
    },
]