export const dataReportesFinalizacion = [
    {
        nro_reporte: 1,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 2,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 3,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 4,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 5,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 6,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 7,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 8,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 9,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 10,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 11,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 12,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },

        {
        nro_reporte: 13,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 14,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
    {
        nro_reporte: 5,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        fecha_entrega: '22/02/2021',
        costo: 800,
    },
]
