export const dataReportes = [
    {
        nro_reporte: 1,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-A',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 2,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-B',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 3,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-C',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 4,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-D',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 5,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-E',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 6,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-F',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 7,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-G',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 8,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-H',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 9,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-I',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 10,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-J',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 11,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-K',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 12,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-L',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 13,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-M',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 14,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-N',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
    {
        nro_reporte: 15,
        empleado_nombre: 'Jose',
        empleado_apellidos:'Calancha',
        neumatico_alfa: '392013-O',
        causa: 'Muy viejo',
        estado: 'Malisimo',
    },
]
