export const dataDocumentoEntrega = [
    {
        nro_orden: 1,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 2,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 3,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 4,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 5,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 6,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 7,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 8,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 9,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 10,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 11,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 12,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
    {
        nro_orden: 13,
        empleado_nombre: 'Jose',
        empleado_apellido:'Calancha',
        extras: 80,
        descuentos: 20,
        referencia:'71237331',
        costo: 3080,
    },
]