export const defaultData = [
    {
        nro_orden: 1,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'PENDIENTE',
    },
    {
        nro_orden: 2,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'FINALIZADO',
    },
    {
        nro_orden: 3,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'PENDIENTE',
    },
    {
        nro_orden: 4,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'PENDIENTE',
    },
    {
        nro_orden: 5,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'PENDIENTE',
    },
    {
        nro_orden: 6,
        nombres: 'Pedro',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'FINALIZADO',
    },
    {
        nro_orden: 7,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'FINALIZADO',
    },
    {
        nro_orden: 8,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'PENDIENTE',
    },
    {
        nro_orden: 9,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'FINALIZADO',
    },
    {
        nro_orden: 10,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'PENDIENTE',
    },
    {
        nro_orden: 11,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'PENDIENTE',
    },
    {
        nro_orden: 12,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'PENDIENTE',
    },
    {
        nro_orden: 13,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'FINALIZADO',
    },
    {
        nro_orden: 14,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'PENDIENTE',
    },
    {
        nro_orden: 15,
        nombres: 'Jose',
        apellidos:'Calancha',
        fecha_creacion: '21/05/2022',
        fecha_entrega: '22/05/2022',
        cotizacion: 90,
        estado: 'PENDIENTE',
    },
]